name: refresh-pinboard-errors

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  refresh-pinboard-errors:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-firefox
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - run: ruby refresh-pinboard-errors.rb
        working-directory: ./pinboard
        env:
          PINBOARD_USERNAME: ${{ secrets.PINBOARD_USERNAME }}
          PINBOARD_PASSWORD: ${{ secrets.PINBOARD_PASSWORD }}
